### ISSUE TITLE
Missing approval status for paypal paid via credit card

### ISSUE THREAD

**Issue by nddsoft** [nopSolutions/2checkout-plugin-for-nopcommerce#1]
Hi,

In the Controllers/PaymentTwoCheckoutController.cs

Line 204, to change the payment status into Paid:
`            if (messageType.ToUpperInvariant() == "FRAUD_STATUS_CHANGED"
&& fraudStatus == "pass"
               && (invoiceStatus == "approved" || paymentType == "paypal ec"))
            {
                newPaymentStatus = PaymentStatus.Paid;
            }`

I've had to add the invoiceStatus == "deposited" on this line:
`&& (invoiceStatus == "approved" || invoiceStatus == "deposited" || paymentType == "paypal ec"))`

Because for some orders with credit cards, this is shown first:
The "approved" is only shown under "ORDER_CREATED"

2Checkout IPN:
sale_id: 
invoice_id: 
**message_type: ORDER_CREATED
invoice_status: approved
fraud_status: wait**
payment_type: credit card
New payment status: Pending

Then followed by below after 8 seconds:
invoice status was changed to "deposited".

2Checkout IPN:
sale_id: 
invoice_id: 
**message_type: FRAUD_STATUS_CHANGED
invoice_status: deposited
fraud_status: pass**
payment_type: credit card
New payment status: Pending

And lastly:

2Checkout IPN:
sale_id: 
invoice_id: 
**message_type: INVOICE_STATUS_CHANGED
invoice_status: deposited
fraud_status: pass**
payment_type: credit card
New payment status: Pending

The credit card gets approved before the fraud status passed.  And when the fraud status pass, the credit card is already marked as deposited, and the payment type did not change to paypal_ec...

Is that correct?

**Comment by RomanovM** [comment]
Solved in https://github.com/nopSolutions/2checkout-plugin-for-nopcommerce/commit/565d721569ca0b16b80b1a4b03468b1f458d9e05
