### ISSUE TITLE
Update configuration instructions

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/2checkout-plugin-for-nopcommerce#2]
3. On the main menu select "Account" then "Site Management".
should become
On the main menu select "Integrations" then "Webhooks & API".

5. Add a new point as below:
In the section "Instant Notification System (INS)" you have to tick the "Enable INS" checkbox.

6. Copy this URL: {GENERATED_URL_HERE} and paste it into "Approved URL".
should be replaced with
Copy this URL: {GENERATED_URL_HERE} and paste it into "Approved URL". Do the same on the "INS Settings" tab.

**Comment by RomanovM** [comment]
Fixed in https://github.com/nopSolutions/2checkout-plugin-for-nopcommerce/commit/0be717fb37dc81adf7d260f1ac3d85fc552b21db
