### ISSUE TITLE
Migration from MD5 to SHA2/SHA3 algorithm

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/2checkout-plugin-for-nopcommerce#4]
Details: https://verifone.cloud/docs/2checkout/API-Integration/01Start-using-the-2Checkout-API/2Checkout-API-general-information/Migration_guide_SHA2_SHA3

**Comment by RomanovM** [comment]
In the plugin we only use INS (Instant Notification Service), and MD5 is still used for hashing in INS, so no need to change it now.

**Comment by skoshelev** [comment]
Closed #4
